### ISSUE TITLE
Replication in Systems.Shared causes the script to hang.

### ISSUE THREAD

**Issue by YourFriendlyError** [meowchun/Roblox-Entity-Component-System#1]
Replacing the while loop back to the original code `system.run = function(entities)` fixes this.

**Comment by meowchun** [comment]
Very late to this, but I also haven't checked notifications in a long time, much less maintained this repository, or framework in general. I went ahead and fixed this issue, but besides fixing bugs, I don't think this will ever be updated again. I wasn't very happy with how this turned out, and if I ever attempt ECS again on Roblox, I plan on approaching it differently.
